language: node_js
env:
- CXX=g++-4.8
os:
- linux
- osx
node_js:
- 8
- 9
- 10
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
sudo: false
before_install:
- if [[ $TRAVIS_OS_NAME == "osx" ]]; then export CXX=clang; fi
- $CXX --version
- PUBLISH_BINARY=false
- echo $TRAVIS_BRANCH
- echo `git describe --tags --always HEAD`
- npm config set progress false
- npm config set spin false
- npm install -g node-gyp node-pre-gyp
install:
- npm install --build-from-source
before_deploy:
- node-pre-gyp package 2>&1
deploy:
  provider: releases
  api_key:
    secure: EGQgyzG41xFYSIob4JwCJEhUhg4VX030r5ZvidOCTYUo9+/XMoS9c6GIKtlGsXiAjcGbUr00W+DaMzTbXp69xO7hfAbGBuojckCCm1upHeFF4EVNNJpd+oWEA3S9i4vG5eja/5Jsdi7xcswocMY+KWqBR4ZeXv7Si9p5kIyW4+zig4G5VuC2iSEWSEG7R4+E9LsLYMpU9/aDBJ8OVHU+bZkLK7vsPsQ4S3AkdW9Y/7ExgrKz26hwsMNFW3kDD3pcfXGF8clK8zTMoEn2KLc4QVDFWLGJ/mW3QfbC+xj5Lo0rKAucjB0ndeC6OHjNLnAmhk7mvy/5E9a2W4TjVl4Pt9zsDL8ztWuUESt2DdxQpdkzYTEuYNtYZY0kekAPEx4OW+zS4xpvX5fBR+Af0FxWkN6bqFly71QOc6P+0IYgwy59c0xQGy/05rnCWzFcz2vJw+7m1WCRJrnTIIjy5knLYWAZeXj2AYCjOcTGL05AiIKMrv/IOILGBVWc8yiH5/kn0cGIDtYu1XL5PownYHOc4EQpgM+FjZwpILnDWzvSpypfVKmIXbxWcFFAu+X+FxlA2GtL5HjWD9Z1iojC4MvHQ70tA4lumsNiVSDTp4urfPYqBE+zpqARLoFYYq/Sk08FHGEIyu28LwDdoilxJLvRW2gpv70r4OpERTXnRNWxljQ=
  file: build/stage/libxmljs/libxmljs/releases/download/**/*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
